version: "3"

services:
  web:
    container_name: web
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    # command: tail -f /dev/null
    ports:
      - "8000:8000"
    volumes:
      - ./mysite:/code
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:13
    pull_policy: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres


volumes:
  postgres_data:
    name: postgres_data
networks:
  default:
    name: django_network
